{
 "title": "Twitter Sentiment Analysis",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tweets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" }
     ],
     "measurement": "status",
     "query": "SELECT count(\"text\") FROM \"status\" WHERE (\"track\" = 'gme') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "text" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "positive",
     "measurement": "status",
     "select": [
      [
       { "params": [ "pos" ], "type": "field" },
       { "params": [ "30" ], "type": "moving_average" }
      ]
     ]
    },
    {
     "alias": "negative",
     "measurement": "status",
     "select": [
      [
       { "params": [ "neg" ], "type": "field" },
       { "params": [ "30" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "moving_avg(neg) by hashtag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "news",
     "measurement": "status",
     "query": "SELECT moving_average(\"neg\", 30) FROM \"status\" WHERE (\"track\" = 'news') AND $timeFilter - 1h",
     "select": [
      [
       { "params": [ "neg" ], "type": "field" },
       { "params": [ "30" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "track", "operator": "=", "value": "news" }
     ]
    },
    {
     "alias": "elon",
     "measurement": "status",
     "query": "SELECT moving_average(\"neg\", 40) FROM \"status\" WHERE (\"track\" = 'elon') AND $timeFilter - 1h",
     "select": [
      [
       { "params": [ "neg" ], "type": "field" },
       { "params": [ "40" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "track", "operator": "=", "value": "elon" }
     ]
    },
    {
     "alias": "gme",
     "measurement": "status",
     "query": "SELECT moving_average(\"neg\", 30) FROM \"status\" WHERE (\"track\" = 'gme') AND $timeFilter - 1h",
     "select": [
      [
       { "params": [ "neg" ], "type": "field" },
       { "params": [ "30" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "track", "operator": "=", "value": "gme" }
     ]
    },
    {
     "alias": "wsb",
     "measurement": "status",
     "query": "SELECT moving_average(\"neg\", 40) FROM \"status\" WHERE (\"track\" = 'wallstreetbets') AND $timeFilter -  1h",
     "select": [
      [
       { "params": [ "neg" ], "type": "field" },
       { "params": [ "40" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "track", "operator": "=", "value": "wallstreetbets" }
     ]
    }
   ]
  },
  {
   "title": "Percentile of negative sentiment",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"neg\", 99) FROM \"status\" WHERE $timeFilter GROUP BY time(30s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}